---
- name: Software
  hosts: groupname
  become: yes
  become_user: root  
  tasks: 
    - name: Install vim
      apt: 
        name: vim
        state: latest
...

---
- name: install Chrome
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/
- name: Install a .deb package
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb